### ISSUE TITLE
Jquery is being loaded twice

### ISSUE THREAD

**Issue by docrinehart** [docrinehart/EverBlog#1]

**Comment by MartynKeigher** [comment]
Where are you seeing this? Is this something to do with the 'ghost' platform or this theme specifically?

**Comment by docrinehart** [comment]
This theme specifically. It was brought to my attention by a reader who noticed it via dev tools. I remember something about jquery being always loaded for hosted ghost, and they were removing that. It could be that was one instance and the theme includes a second, but I need to investigate to be sure. 

Related: https://dev.ghost.org/no-more-jquery/

**Comment by docrinehart** [comment]
I did a quick look, and indeed ghost added jquery in the code injection footer as well as the theme includes it under assets. I've opted to remove it from the injection so that it remains included in the theme for consistency and ease of configuration when updating the theme.
