### ISSUE TITLE
Project still live?? 

### ISSUE THREAD

**Issue by MartynKeigher** [docrinehart/EverBlog#8]
I see a few thing you want to do to this code, and I don't mind getting stuck in and helping!!

I spun up a Ghost blog today and THIS theme is exactly what I need to get my OneNote/EverNote stuff out of those platforms.

**Comment by docrinehart** [comment]
Awesome! I actually forked this so that I could keep it up to date for my own blog, but if you feel like contributing, feel free to fork it and submit any PRs and I'll take a look as soon as I'm able.
